name: Build and Test

on:
  pull_request:
    branches:
      - main
on:
  push:
    branches:
      - local-dependencies

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake build-essential libglfw3-dev libglu1-mesa-dev libgtest-dev xvfb
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libglfw3-dev libglu1-mesa-dev libgtest-dev

          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: xvfb-run -s "-screen 0 1920x1080x24" ctest --test-dir build --output-on-failure
